---
- name: Install required packages
  hosts: webserver
  remote_user: tcAdmin
  become: true

  tasks:
    - name: Update apt repositiories cache and install nginx
      apt:
        name: nginx
        update_cache: yes

    - name: Install OpenSSL
      apt:
        name: openssl

- name: Create nginx server block
  hosts: webserver
  remote_user: tcAdmin
  become: true

  tasks:
    - name: Create server block directory
      file:
        path: /var/www/{{ ansible_host }}/html
        state: directory
        owner: tcAdmin
        group: tcAdmin

    - name: Change permissions of parent directory
      file:
        path: /var/www/{{ ansible_host }}
        mode: '0755'

    - name: Copy html file to webserver
      copy:
        src: evt-web.html
        dest: /var/www/{{ ansible_host }}/html/index.html
        owner: tcAdmin
        group: tcAdmin
        mode: '0755'

    - name: Update nginx.conf for server blocks
      copy:
        src: nginx.conf
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root
        mode: '0644'

- name: Configure nginx for self-signed SSL
  hosts: webserver
  remote_user: tcAdmin
  become: true

  tasks:
    - name: Generate private key (RSA, 4096 bits)
      community.crypto.openssl_privatekey:
        path: /etc/ssl/private/nginx-selfsigned.key

    - name: Create certificate signing request (CSR) for self-signed certificate
      community.crypto.openssl_csr_pipe:
        privatekey_path: /etc/ssl/private/nginx-selfsigned.key
        common_name: "{{ ansible_host }}"
      register: csr
    
    - name: Create self-signed certificate from CSR
      community.crypto.x509_certificate:
        path: /etc/ssl/certs/nginx-selfsigned.crt
        csr_content: "{{ csr.csr }}"
        privatekey_path: /etc/ssl/private/nginx-selfsigned.key
        provider: selfsigned

    - name: Generate Diffie-Hellman parameters with the 4096-bit size (this step may take a few minutes)
      community.crypto.openssl_dhparam:
        path: /etc/nginx/dhparam.pem

    - name: Create nginx configuration snippet for self-signed certificate
      copy:
        src: self-signed.conf
        dest: /etc/nginx/snippets/self-signed.conf
        owner: tcAdmin
        group: tcAdmin
        mode: '0644'

    - name: Create nginx configuration for SSL settings
      copy:
        src: ssl-params.conf
        dest: /etc/nginx/snippets/ssl-params.conf
        owner: tcAdmin
        group: tcAdmin
        mode: '0644'

    - name: Update server block with SSL
      copy:
        src: server_block
        dest: /etc/nginx/sites-available/{{ ansible_host }}
        owner: tcAdmin
        group: tcAdmin
        mode: '0644'

    - name: Enable server block with symlink
      command: sudo ln -s /etc/nginx/sites-available/{{ ansible_host }} /etc/nginx/sites-enabled/

    - name: Reload nginx to make configuration changes
      command: nginx -s reload